### ISSUE TITLE
bug in rearranging location events

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/calendar-assistant#113]
Given I have a two-day location event (today and tomorrow)
And my plans change
When I set location for today
I shouldn't see an error message in the CLI:

```
calendar-assistant $ ca location-set NJ today
Traceback (most recent call last):
	43: from /home/flavorjones/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	42: from /home/flavorjones/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	41: from /home/flavorjones/.rvm/gems/ruby-2.6.0/bin/calendar-assistant:23:in `<main>'
	40: from /home/flavorjones/.rvm/gems/ruby-2.6.0/bin/calendar-assistant:23:in `load'
	39: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/bin/calendar-assistant:10:in `<top (required)>'
	38: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	37: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	36: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	35: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	34: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/cli/commands.rb:223:in `location_set'
	33: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/cli/commands.rb:273:in `calendar_assistant'
	32: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/cli/command_service.rb:17:in `calendar_assistant'
	31: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:45:in `in_env'
	30: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/config.rb:76:in `in_env'
	29: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:46:in `block in in_env'
	28: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:53:in `in_tz'
	27: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:23:in `in_tz'
	26: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:54:in `block in in_tz'
	25: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:47:in `block (2 levels) in in_env'
	24: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/cli/command_service.rb:18:in `block in calendar_assistant'
	23: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/cli/commands.rb:224:in `block in location_set'
	22: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:91:in `create_location_events'
	21: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:91:in `each'
	20: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/calendar_assistant.rb:92:in `block in create_location_events'
	19: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/location_event_repository.rb:22:in `create'
	18: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/location_event_repository.rb:30:in `modify_location_events'
	17: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/location_event_repository.rb:30:in `each'
	16: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/location_event_repository.rb:34:in `block in modify_location_events'
	15: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/calendar-assistant-0.9.0/lib/calendar_assistant/event_repository.rb:57:in `update'
	14: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/generated/google/apis/calendar_v3/service.rb:1656:in `update_event'
	13: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
	12: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:102:in `execute'
	11: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	10: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 9: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 8: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:110:in `block in execute'
	 7: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
	 6: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
	 5: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
	 4: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
	 3: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:309:in `execute_once'
	 2: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:193:in `process_response'
	 1: from /home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/api_command.rb:116:in `check_status'
/home/flavorjones/.rvm/gems/ruby-2.6.0/gems/google-api-client-0.28.4/lib/google/apis/core/http_command.rb:228:in `check_status': required: Missing end time. (Google::Apis::ClientError)
```

**Comment by flavorjones** [comment]
Note that the new event gets created, it's just that the old event is not truncated.
